name: api server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: execute remote ssh
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/docker
            sudo docker-compose up -d
            cd ~/repo/api_server
            git pull
            source ~/.nvm/nvm.sh
            npm ci
            npm run build
            pm2 start dist/main.js --name api_server
